# good-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment
  labels:
    env: prod  # Respecte K8sRequiredLabels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          securityContext:
            runAsUser: 1000  # Non-root (respecte K8sBlockRootContainers)
            capabilities:
              drop: ["ALL"]  # Aucune capacité dangereuse
          resources:
            limits:  # Respecte K8sResourceLimits
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:  # Respecte K8sRequireProbes
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: good-service
  annotations:
    security.kubernetes.io/enforce-tls: "true"  # Respecte K8sRequiredServiceAnnotations
spec:
  selector:
    app: nginx
  ports:
    - port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: good-secret
  annotations:
    security
.kubernetes.io/encrypted: "true"  # Respecte KBSSecretsBase64
data:
  password: RkFLRV9FTkNSWVBURURfREFUQQ==  # Données "chiffrées" (exemple)
