apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredServiceAnnotations
metadata:
  name: require-service-tls-annotation
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
