apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockBadNodeAffinity
metadata:
  name: block-experimental-node-affinity
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
